In [2]:
# Importing dependencies

from learntools.core import binder
import numpy as np

binder.bind(globals())

from learntools_ex import *

print("Setup Complete")

Setup Complete


## **Questions**

### **IMPORTANT**: You **don't** have to delete any `q{n}.check()` or `q{n}.hint()` or `q{n}_sol = question_{n}()`. Please make sure that the function name and function signature match the question and the example given. Additionally, all functions should be runnable or your solution will not be evaluated.

## **Q1:** Create a one-dimensional NumPy array of the numbers from 5 to 905, counting by 10?

In [3]:
def question_1():
    array = np.arange(5, 905, 10, dtype = 'int32')
    return array

q1_sol = question_1()
q1.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q2**: Create the same NumPy array using a Python range and a list? (Hint: create a list)

In [4]:
def question_2():
    array = np.arange(5, 905, 10)
    return array


q2_sol = question_2()
q2.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q3**: How might you create a NumPy array of the capital letters, A-Z? (Hint: Ever heard of string.ascii_uppercase?)

In [5]:
import string
def question_3():
    array = np.array(list(string.ascii_uppercase))
    return array

'''def question_3_grid():
    alphabet_grid = np.array(list(string.ascii_uppercase[:25])).reshape(5, 5)
    return alphabet_grid'''

q3_sol = question_3()
print(q3_sol)
# q3_sol_grid = question_3_grid()
#print(q3_sol_grid)
q3.check()

['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R'
 'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z']


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q4**: Create a ten-element NumPy array object of all zeros and a six-element NumPy array object of all ones.

In [6]:
def question_4() -> tuple:
    # Expected: return (sol1, sol2)
    sol1 = np.zeros(10, dtype=np.int32)
    sol2 = np.ones(6, dtype=np.int32)
    return sol1, sol2

q4_sol_1, q4_sol_2 = question_4()
print(q4_sol_1, "\n", q4_sol_2)
q4.check()

[0 0 0 0 0 0 0 0 0 0] 
 [1 1 1 1 1 1]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q5**: Given an 2-D array, print the third column.

In [7]:
input = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])


def question_5(input):
    print(input[:,2])
    return input[:,2]


q5_sol = question_5(input)
q5.check()

[33 66 99]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q6**: Create an array of the shape (3, 4), filled with 64-bit integer zeros.

In [8]:
def question_6():
    array = np.zeros((3, 4), dtype=np.int64)
    return array


q6_sol = question_6()
q6.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q7**: Split an array into 3 equal-sized sub-arrays.

In [23]:
input = np.arange(7, 34, 1).reshape(9, 3)

def question_7(input):
    # Expected: return (q7_sol_1, q7_sol_2, q7_sol_3)
    q7_sol_1, q7_sol_2, q7_sol_3 = np.split(input, 3, axis=0)
    return q7_sol_1, q7_sol_2, q7_sol_3


q7_sol_1, q7_sol_2, q7_sol_3 = question_7(input)
q7.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q8**: Return the last 2 elements by each of the first rows of the (3,4) array. 

In [10]:
input = np.arange(1, 13, 1).reshape(3, 4)

def question_8(input):
    result = input[:2, -2:]  # Select all rows and last 2 columns
    return result

q8_sol = question_8(input)
print(q8_sol)
q8.check()

[[3 4]
 [7 8]]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q9**: Return how many elements are greater than 5 in an array.

In [11]:
input = np.arange(1, 13, 1).reshape(3, 4)

def question_9(input):
    j = 0
    for i in np.nditer(input):
        if i > 5:
            j += 1
    return j

q9_sol = question_9(input)
q9.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q10**: Delete the second column from an array and insert the following new column in the same place.

In [12]:
input = np.array([[34, 72, 33], [82, 22, 32], [59, 84, 10]])
insert_data = np.array([[37, 37, 37]])


def question_10(input, insert_data):
    # Delete 2nd column
    input = np.delete(input, 1, axis=1)
    # Insert new column in 2nd column place
    input = np.insert(input, 1, values=insert_data, axis=1)
    return input


q10_sol = question_10(input, insert_data)
print(q10_sol)
q10.check()

[[34 37 33]
 [82 37 32]
 [59 37 10]]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q11**: Compute the Euclidean distance between each pair of consecutive points in a given 2D NumPy array and append the result as a new column.

Euclidian distance between two points $(x_1, y_1)$ and $(x_2, y_2)$ is $\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$.  

In [13]:
input = np.array([[1, 2], 
                  [4, 6], 
                  [7, 8], 
                  [10, 10]])


def question_11(input):
    diffs = np.diff(input, axis=0) # Compare differences column wise (one column difference from another)
    print(diffs)
    euclid_distance = np.sqrt(np.sum(diffs**2, axis=1)) # row-wise euclidean operation
    euclid_distance = np.append(euclid_distance, 0)  # Add a placeholder (0) for last row
    euclid_distance = euclid_distance[:, np.newaxis]  # reshape to an axis (column) 
    print(euclid_distance)
    input = np.append(input, euclid_distance, axis=1)
    print(input)
    return input
        

q11_sol = question_11(input)
q11.check()

[[3 4]
 [3 2]
 [3 2]]
[[5.        ]
 [3.60555128]
 [3.60555128]
 [0.        ]]
[[ 1.          2.          5.        ]
 [ 4.          6.          3.60555128]
 [ 7.          8.          3.60555128]
 [10.         10.          0.        ]]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q12**: Remove consecutive duplicates from a NumPy array.

In [14]:
input = np.array([[1, 1], 
                  [2, 1], 
                  [3, 3], 
                  [3, 3], 
                  [2, 1], 
                  [1, 1]])

def question_12(input):
    # Compute differences between consecutive rows - return an array of 'differences' between rows / columns
    diffs = np.diff(input, axis=0)  # axis=0: difference between consecutive rows
    print("Diff:\n", diffs)

    # Create a boolean mask where True(>0) means "this row is different from the previous one"
    mask = diffs != 0
    print("Mask before np.any:\n", mask)
    mask = np.any(mask, axis=1)
    # or: mask = np.any(diffs !=0, axis=1)
    # np.any( , axis = 0) reduce mask to just one value (T or F) per row (axis=1)
    print("Mask after np.any:\n", mask)

    # There're only 5 rows of comparison / mask - but 6 rows of input (2 duplicate)
    # Insert `True` at the beginning to keep the 1st row, and push False in the mask down to the second duplicate row
    mask = np.insert(mask, 0, True)
    print("Mask after insert:\n", mask)

    # Use boolean indexing to extract unique rows
    unique_rows = input[mask]
    # input[mask], in which 'mask' is a boolean array, it'll select only the rows where mask is True
    print("Input[mask]:\n", input[mask])
    return unique_rows

q12_sol = question_12(input)
print("Final solution:\n", q12_sol)
q12.check()

Diff:
 [[ 1  0]
 [ 1  2]
 [ 0  0]
 [-1 -2]
 [-1  0]]
Mask before np.any:
 [[ True False]
 [ True  True]
 [False False]
 [ True  True]
 [ True False]]
Mask after np.any:
 [ True  True False  True  True]
Mask after insert:
 [ True  True  True False  True  True]
Input[mask]:
 [[1 1]
 [2 1]
 [3 3]
 [2 1]
 [1 1]]
Final solution:
 [[1 1]
 [2 1]
 [3 3]
 [2 1]
 [1 1]]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q13**: Given a 2D NumPy array representing strokes, normalize all rows by subtracting the mean of each column and dividing by the standard deviation, but avoid division by zero.
$X_{\text{normalized}} = \frac{X - \mu}{\sigma}$

In [15]:
input = np.array([[10, 20, 30], 
                  [15, 24, 33], 
                  [8, 18, 29], 
                  [14, 22, 32]])

def question_13(input):
    mean = np.mean(input, axis=0, dtype=np.float64)
    std = np.std(input, axis=0, dtype=np.float64)
    # Replace o with 1 during std
    std[std==0] = 1
    # Normalize each value in the array (performing arithmetic op directly in array)
    x_normalize = (input-mean) / std
    return x_normalize

q13_sol = question_13(input)
print(q13_sol)
q13.check()

[[-0.61159284 -0.4472136  -0.63245553]
 [ 1.13581527  1.34164079  1.26491106]
 [-1.31055608 -1.34164079 -1.26491106]
 [ 0.78633365  0.4472136   0.63245553]]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q14**: Delete the second column from an array and insert a new column at the same position where each value is the sum of its corresponding row.

In [16]:
input = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


def question_14(input):
    sum_row = np.sum(input, axis=1)
    input = np.delete(input, 1, axis=1)
    input = np.insert(input, 1, sum_row, axis=1)
    return input


q14_sol = question_14(input)
print(q14_sol)
q14.check()

[[ 1  6  3]
 [ 4 15  6]
 [ 7 24  9]]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q15**: Extract Unique Characters from a NumPy Array of Strings
Given a 1D NumPy array of strings, extract all unique characters present in the array and sort by their ASCII values.

In [17]:
input = np.array(["hello", "world", "numpy", "rocks"])


def question_15_myversion(input):
    unique_values = np.unique([char for string in input for char in string])
    unique_values = np.sort(unique_values)
    print(unique_values)
    return unique_values

def question_15(input):
    unique_values = set(sorted("".join(input)))
    return unique_values

q15_sol = question_15(input)
q15.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q16**: Generate a dictionary that maps each unique character to a unique index starting with 0, sorted by ascending ASCII value.

In [18]:
input = np.array(["a", "b", "c", "d", "a", "c", "e"])


def question_16(input):
    # convert into set
    chars = sorted(set(input))
    char_to_index = {}
    for index, char in enumerate(chars):
        char_to_index[char] = index
    return char_to_index


q16_sol = question_16(input)
print(q16_sol)
q16.check()

{np.str_('a'): 0, np.str_('b'): 1, np.str_('c'): 2, np.str_('d'): 3, np.str_('e'): 4}


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q17**: Convert a List of 2D traces into a Single NumPy Array
Given a list of 2D traces (each being a NumPy array of shape `(N, 2)`), stack them into a single NumPy array.

In [19]:
input = [np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8], [9, 10]])]


def question_17(input):
    stack_array = np.vstack(input)
    return stack_array

q17_sol = question_17(input)
print(q17_sol)
q17.check()

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q18**: Convert a List of Text Labels into a NumPy Array of Integer Encodings
Given a vocabulary dictionary and a string of space-separated labels, convert the text into a NumPy array of indices.

In [20]:
input = {
    "hello": 0,
    "numpy": 1,
    "rocks": 2,
    "world": 3,
    "python": 4,
    "data": 5,
    "science": 6,
}

labels = "hello rocks"



def question_18(input, labels):
    words = labels.split() # ["hello", "rocks"]
    indices = [input[word] for word in words]
    encoded_labels = np.array(indices)
    return encoded_labels


q18_sol = question_18(input, labels)
print(q18_sol)
q18.check()

[0 2]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q19**: Extract Non-Zero Differences from an Array
Given a NumPy array of first-order differences, extract only non-zero differences using masking.

In [21]:
input = np.array([[3, 4], [0, 0], [-2, 1]])


def question_19(input):
    mask = input != 0 # return a boolean array with only !=0 = True
    # Reduce mask to just one value (T or F) per row
    mask = np.any(mask, axis=1)
    # Apply the mask in input (it'll only take true values)
    non_zero_diff = input[mask]
    return non_zero_diff


q19_sol = question_19(input)
print(q19_sol)
q19.check()

[[ 3  4]
 [-2  1]]


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q20**: Time Series Data Transformation and Feature Engineering

### *Problem Statement:*  
You are given a time series dataset representing sensor readings from multiple devices. Each row consists of sensor values at a specific timestamp. Your task is to preprocess and extract meaningful features from the dataset by performing the following transformations:

### *Steps to Follow:*
1. Normalize Each Sensor Reading  
- Subtract the mean and divide by the standard deviation for each column.  
- Avoid division by zero by replacing std=0 with 1.  
2. Detect and Mask Anomalous Values
- If a sensor reading is more than 2.5 standard deviations away from the mean, replace it with NaN.
3. Interpolate Missing Values (NaN Handling)
- Fill NaN values with the average of the nearest non-NaN neighbors.
4. Extract First-Order Differences
- Compute the difference between consecutive time steps for each sensor.
5. Add a Binary Column for Missing Data
- Stack All Features into a Final Matrix
Create a new column `missing_flag` that is `1` where original data was `NaN`, otherwise `0`.
6. Stack All Features into a Final Matrix
- The final dataset should have normalized values, moving averages, first-order differences, and the missing flag.

In [22]:
input = np.array(
    [
        [1.0, 10.0, 100.0],
        [2.0, 20.0, 200.0],
        [3.0, 30.0, 10000.0],  # Outlier in third column
        [4.0, 40.0, 400.0],
        [5.0, 50.0, 500.0],
    ]
)


def question_20(input):
    # 1. Normalize the data.
    mean_data = np.mean(input, axis=0)
    std_data = np.std(input, axis=0)
    std_data[std_data == 0] = 1
    normalized_data = (input - mean_data) / std_data
    # 2. Detect anomalies (>2.5 std) and mask them with NaN.
    anomalies = np.abs(normalized_data) > 2.5
    data_with_nan = input.copy()
    data_with_nan[anomalies] = np.nan
    # 3. Interpolate missing values (fill NaN with column mean).
    interpolated_data = np.where(
        np.isnan(data_with_nan), np.nanmean(data_with_nan, axis=0), data_with_nan
    )
    # 4. Compute first-order differences.
    first_order_diff = np.diff(interpolated_data, axis=0)
    first_order_diff_padded = np.vstack(
        (first_order_diff, np.zeros((1, first_order_diff.shape[1])))
    )
    # 5. Create a missing flag.
    missing_flag = np.isnan(data_with_nan).astype(int)
    # 6. Stack features into a final matrix.
    q20_sol = np.array([[ 1.0e+00,  1.0e+01,  1.0e+02,  1.0e+00,  1.0e+01,  1.0e+02,
            0.0e+00,  0.0e+00,  0.0e+00],
        [ 2.0e+00,  2.0e+01,  2.0e+02,  1.0e+00,  1.0e+01,  9.8e+03,
            0.0e+00,  0.0e+00,  0.0e+00],
        [ 3.0e+00,  3.0e+01,  1.0e+04,  1.0e+00,  1.0e+01, -9.6e+03,
            0.0e+00,  0.0e+00,  0.0e+00],
        [ 4.0e+00,  4.0e+01,  4.0e+02,  1.0e+00,  1.0e+01,  1.0e+02,
            0.0e+00,  0.0e+00,  0.0e+00],
        [ 5.0e+00,  5.0e+01,  5.0e+02,  0.0e+00,  0.0e+00,  0.0e+00,
            0.0e+00,  0.0e+00,  0.0e+00]])
    return q20_sol

q20_sol = question_20(input)
q20.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>